### ISSUE TITLE
dynamic createExecutor

### ISSUE THREAD

**Issue by alecgorge** [masteroftime/Python-Plugin-Loader#1]
So that you don't have to keep updating this plugin every time there is a new event, you probably want to do something like this: https://github.com/Zeerix/RubyBukkit/blob/master/src/org/notbukkit/RubyPluginLoader.java#L178 and https://github.com/Zeerix/RubyBukkit/blob/master/src/org/notbukkit/RubyPluginLoader.java#L62

**Comment by masteroftime** [comment]
Thanks alot. I was looking for a way to do this and you saved me lots of work.
