### ISSUE TITLE
Self in Bukkit Functions?

### ISSUE THREAD

**Issue by wgaylord** [masteroftime/Python-Plugin-Loader#13]
When you call a function from bukkit like
import org.bukkit as Bukkit

Bukkit.World.getBlockAt(1,1,1).setType("Stone")

Says  TypeError: getBlockAt(): expected 2 or 4 args; got 3 so I added a empty string in then it said TypeError: getBlockAt(): self arg can't be coerced to org.bukkit.World

after days of looking I could find no fix for this even looking at bukkit and this plugins code nothing.

**Comment by masteroftime** [comment]
It looks like you're calling getBlockAt() lika a static method, which it isn't.

You have to get a reference to the world first and then you can call the .getBlockAt() using this reference. The way you obtain the reference to the wolrd depends on the situation. You could get the world the player is currently in by using the .getWorld() method on the player. Or you could use the .getWorld(name) method of the Bukkit class to get the World with the specified name. It is also possible to get a list of all worlds on the server by using .getWorlds() also in the Bukkit class.

Here is an example, how to retrieve the world with the name 'world' (which I think is the default, but I'm not sure) and then call the .getBlockAt() method:

``` python
from org.bukkit import Bukkit

world = Bukkit.getWorld('world')
world.getBlockAt(1,1,1)
```

I hope this solves your problem.

**Comment by wgaylord** [comment]
I was looking for the getWorld on the wiki that same day I must have derped because I have a mod I code and I have to do that too.

**Comment by gdude2002** [comment]
@chibill If your problem's solved, you should probably close your ticket, so the issues page doesn't have incomplete issues there. It looks bad. :P
